### ISSUE TITLE
Can't upgrade from apache 2.4.16 to 2.4.18

### ISSUE THREAD

**Issue by davideradice** [Homebrew/homebrew-apache#102]
After
```
$ brew update && brew upgrade && brew cleanup && brew doctor
```

With 
```
 brew upgrade httpd24
```

I get 
```
Error: homebrew/apache/httpd24 2.4.16 already installed
```

Here is my configuration:
```
Mac OS X
10.11.2

Apache
Server version: Apache/2.4.16 (Unix)
Server built:   Nov 18 2015 08:11:11

Mysql
mysql  Ver 14.14 Distrib 5.7.10, for osx10.11 (x86_64) using EditLine wrapper

Brew
Homebrew 0.9.5 (git revision 4cf94; last commit 2015-12-21)

PHP for Apache
X-Powered-By
PHP/7.0.0RC3

Xcode
Xcode 7.2
Build version 7C68

GCC
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

PHP command line
PHP 7.0.0RC3 (cli) (built: Dec  1 2015 15:43:07)
```

Thank you!

**Comment by lukejanicke** [comment]
According to [Issue 95 (closed)](https://github.com/Homebrew/homebrew-apache/issues/95), there was a major flaw in Apache 2.4.17. So Homebrew reverted to Apache 2.4.16 in [Pull 96 (closed)](https://github.com/Homebrew/homebrew-apache/pull/96). The flaw was supposed to have been fixed in Apache 2.4.18. I don’t know if it was. Either way, Homebrew hasn’t been updated, yet.

**Comment by lukejanicke** [comment]
Furthermore, if you do happen to successfully “upgrade” the default Apache 2.4.16 to the Homebrew Apache 2.4.16, the new Apache configuration files will be in `$(brew --prefix)/etc/apache2/2.4`.

If you try editing the default `http.conf` in `/etc/apache2`, you’ll notice nothing happens. This stumped me for a while until I read [homebrew-apache](https://github.com/Homebrew/homebrew-apache/blob/master/README.md) README carefully.

`$(brew --prefix)` probably resolves to `/usr/local`.

Look for `http.conf` in `/usr/local/etc/apache2/2.4`.

**Comment by davideradice** [comment]
Dear lukejanicke,

you're right, in december I've successfully "upgraded" to Homebrew Apache .16 and found out the new position of conf files.

I've updated my bash aliases:
```
apacheconf='sudo subl /usr/local/etc/apache2/2.4/httpd.conf'
vhostsconf='sudo subl /usr/local/etc/apache2/2.4/extra/httpd-vhosts.conf'
````

Thank you.

**Comment by lukejanicke** [comment]
There are other **httpd.conf** differences between default and Homebrew versions.

One that almost had me buying a third coffee today...

Default **httpd.conf** configures `Listen 80`.
Homebrew **httpd.conf** configures `Listen 8080`.

**Comment by lukejanicke** [comment]
Can a maintainer chime in on whether **homebrew-apache** will get a 2.4.18 update?

**Comment by dunn** [comment]
If you want to send a pull request that'd be great! Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions.
