### ISSUE TITLE
brew install -v homebrew/apache/mod_fastcgi fails

### ISSUE THREAD

**Issue by epavletic** [Homebrew/homebrew-apache#113]
I ran into trouble when trying to install `mod_fastcgi` with a updated Homebrew on a fresh OSX El Capitan build. When excecuting `brew install -v homebrew/apache/mod_fastcgi --with-brewed-httpd22` I get the following result:
```
==> Installing mod_fastcgi from homebrew/apache
Warning: homebrew/apache/mod_fastcgi: --with-brewed-httpd22 was deprecated; using --with-homebrew-httpd22 instead!
==> Downloading http://www.fastcgi.com/dist/mod_fastcgi-2.4.6.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "mod_fastcgi"
Download failed: http://www.fastcgi.com/dist/mod_fastcgi-2.4.6.tar.gz
```
Attempting to install without the `--with-homebrew-httpd22`-flag yield the same results. Any ideas? The message is pretty straight forward – I'm just not sure what to do next? Is the absence of the file related to #47, #48 and #84 maybe? I actually did another clean install  with El Capitan a few months back, and its running `mod_fastcgi` 2.4.6 without any issues…

**Comment by epavletic** [comment]
Looking at the fastcgi.com-domain it seems as it has expired or something – [this WayBackMachine-snapshot](http://web.archive.org/web/20160310064103/http://www.fastcgi.com/drupal/) from the beginning of March looks more like the proper site, in comparison to what shows up when you visit it [today](http://www.fastcgi.com/).

**Comment by DomT4** [comment]
Hacked around it via https://github.com/Homebrew/homebrew-apache/commit/0ee1dd9012f506897ef75ca6f2a559d19576d709 for now.
