### ISSUE TITLE
Unable to load mod_http2

### ISSUE THREAD

**Issue by benjaminblack** [Homebrew/homebrew-apache#114]
This is for httpd24 on OS X 10.11.3.

Compiled with options --with-http2, --with-mpm-worker, --with-privileged-ports. The build completes with no errors, and the server functions normally, except that I am unable to load mod_http2.

In httpd.conf, on line 172 (after all the other module include lines), I have added:

`LoadModule mod_http2 libexec/mod_http2.so`

But apachectl configtest reports the following:

`httpd: Syntax error on line 172 of /usr/local/etc/apache2/2.4/httpd.conf: Can't locate API module structure 'mod_http2' in file /usr/local/opt/httpd24/libexec/mod_http2.so: dlsym(0x7f9253600b70, mod_http2): symbol not found`

**Comment by kabel** [comment]
Try `LoadModule http2_module libexec/mod_http2.so` in your config instead. I don't think `mod_http2` is the correct module identifier.

**Comment by hainuo** [comment]
@kabel    the http2 of apache  httpd is depends on nghttp2    i have brew install nghttp2 but  i can't find the mod_http2.so

**Comment by kabel** [comment]
@hainuo you must install `httpd24` with the the `--with-http2` option in order to get the `mod_http2.so` file. Try `brew reinstall httpd24 --with-http2`

**Comment by hainuo** [comment]
@kabel   thanks
