### ISSUE TITLE
envvars file containing incorrect path

### ISSUE THREAD

**Issue by javian** [Homebrew/homebrew-apache#115]
After installing httpd24 there's a file called envvars in the `/usr/local/etc/apache2/2.4` directory. This file contains the following script

```
if test "x$DYLD_LIBRARY_PATH" != "x" ; then
  DYLD_LIBRARY_PATH="/usr/local/Cellar/httpd24/2.4.18/libexec:$DYLD_LIBRARY_PATH"
else
  DYLD_LIBRARY_PATH="/usr/local/Cellar/httpd24/2.4.18/libexec"
fi
export DYLD_LIBRARY_PATH
```

The path in this file points to a directory inside the the apache directory. Shouldn't this envvars file be pointing to a lib directory (/usr/local/lib or /usr/lib) just as the stock envvars file that comes with OSX does ?

**Comment by MikeMcQuaid** [comment]
We just delete this file in the `httpd` core formula now.
