### ISSUE TITLE
macos 10.12 安装 Apache 出错

### ISSUE THREAD

**Issue by hainuo** [Homebrew/homebrew-apache#122]
```
┌─<hainuo @ liufengdeMacBook-Air in ~>
└─<>──» brew install homebrew/apache/httpd24                                                                      1 < 21:50:25
==> Tapping homebrew/apache
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-apache'...
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 15 (delta 6), reused 6 (delta 0), pack-reused 0
Unpacking objects: 100% (15/15), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-apache/mod_suexec.rb
formulae require at least a URL
Error: Cannot tap homebrew/apache: invalid syntax in tap!
```

**Comment by deepj** [comment]
The same problem here!

**Comment by ksom** [comment]
Same problem here !

**Comment by javian** [comment]
Is this still an issue ?

**Comment by alexvb** [comment]
Yes, still running into this issue on macOS Sierra Beta 7 (16A313a).

**Comment by javian** [comment]
This looks like a similar issue https://github.com/Homebrew/homebrew-science/issues/4172 - can  you try the solution posted there and see if it works ?

**Comment by mjsamberg** [comment]
The http24 build works fine. I think the problem is in the file "mod_suexec.rb". It doesn't look like there's a switch for Sierra...

**Comment by M0rtenB** [comment]
Same problem here, on Sierra gm

**Comment by hainuo** [comment]
in new version of homebrew it works well

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated in favour of the `httpd` formula installed and working after https://github.com/Homebrew/homebrew-core/pull/17726 (which works on Sierra and High Sierra).
