### ISSUE TITLE
Apache fails to load `php5_module`

### ISSUE THREAD

**Issue by romeoartista** [Homebrew/homebrew-apache#123]
Installed `Apache 2.4` and `PHP 5.6` without any options.

I get the error message below in attempting to start Apache.

`httpd: Syntax error on line 172 of /usr/local/etc/apache2/2.4/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Symbol not found: _unixd_config\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Expected in: /usr/local/bin/httpd\n in /usr/local/opt/php56/libexec/apache2/libphp5.so`

**Comment by javian** [comment]
Can you put in some more information about your system ?

**Comment by timsnadden** [comment]
I am getting a similar problem apart from for me it's with apache 2.2 and php 5.3. The libexec directory is not being created. `apachectl configtest` returns OK if I remove the following line.

`LoadModule php5_module        libexec/libphp5.so`

Previously the php module was created and located in the following location `/usr/local/opt/php53/libexec/apache2/libphp5.so`. 

I tried reinstalling php53 with the `--with-apache22` flag but it still didn't create the apache module.

**Comment by javian** [comment]
Just note that the php5.3 and apache 2.2 bottles have not been merged yet which might be related.

**Comment by tangerine62** [comment]
maybe you can just the --with-apache option when installing php

**Comment by lekkerduidelijk** [comment]
Bumped into the same issue. As described in the [homebrew-php](https://github.com/Homebrew/homebrew-php/issues/3629) repo, the next steps fixed my issues.

I ran:
`brew uninstall --force httpd24` 
and 
`brew uninstall --force php56` 
to remove all versions of Apache 2.4 and PHP 5.6.

Then:
`brew install php56 --with-apache` 

And after installation: 
`brew services restart httpd24`

Hope it helps.

**Comment by romeoartista** [comment]
@javian @timsnadden @tangerine62 @lekkerduidelijk 

Hello, everyone.

Got this working by including thr `--with-apache` option as some of you have mentioned. Thanks for the help!

**Comment by jameslbrown** [comment]
Not working for me. MacOS X 10.11.6. Have tried with PHP 5.6, 7.0 & 7.1.0RC3:

```
brew install php71 --with-apache
==> Installing php71 from homebrew/php
==> Downloading https://downloads.php.net/~davey/php-7.1.0RC3.tar.bz2
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/php71/7.1.0-rc.3_8 --localstatedir=/usr/local/var --sysconfdir=/usr/local/etc/php/7.1 --with-config-file-path=/usr/local/etc
Last 15 lines from /Users/jlbrown/Library/Logs/Homebrew/php71/01.configure:
--enable-dtrace
--disable-phpdbg
--enable-zend-signals

configure: WARNING: unrecognized options: --with-mysql
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... (cached) sed
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking target system type... x86_64-apple-darwin15.6.0
checking whether the C compiler works... no
configure: error: in `/private/tmp/php71-20161026-40548-x4gvnk/php-7.1.0RC3':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by clarkw** [comment]
For php53 and httpd22, this is still not working.

I force remove httpd22 and php53.
I also removed the /usr/local/etc/php/5.3 and /usr/local/etc/apache2/2.2 directories.

Then
`brew install php53 --with-apache22
`
The installation completes successfully, but /usr/local/Cellar/php53/5.3.29_7/libexec/apache2/libphp5.so does not exist.

Although, I need apache22, I also tried 
`brew install php53 --with-apache
`
The installation completes successfully, and the apache module is created, but the apache module does not load when going to php enabled pages.

I don't understand brew well enough to know what is going on. Any suggestions are appreciated.

**Comment by donnamcmaster** [comment]
Thanks for the help, folks. Just one note that Homebrew has deprecated the `--with-apache` modifier: 
`$ brew install php56 --with-apache
==> Installing php56 from homebrew/php
Warning: homebrew/php/php56: --with-apache was deprecated; using --with-httpd24 instead!
`
