### ISSUE TITLE
Error installing homebrew/apache/ab

### ISSUE THREAD

**Issue by vikrantrathore** [Homebrew/homebrew-apache#130]
When installing ab benchmark tool of apache get an error:

`usr/local/opt/apr/libexec/build-1/libtool --tag CC --mode=link clang  -g -O2   -lssl -lcrypto -lpthread  \
	         -o ab  ab.lo       /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
libtool: link: cannot find the library `/usr/local/Cellar/apr/1.5.2_2/libexec/lib/libapr-1.la' or unhandled argument `/usr/local/Cellar/apr/1.5.2_2/libexec/lib/libapr-1.la'
make: *** [ab] Error`

**Comment by ryanli1994** [comment]
A temp fix:
`cp -R /usr/local/Cellar/apr/1.5.2_3/ /usr/local/Cellar/apr/1.5.2_2/`

**Comment by javian** [comment]
The bottles needs to be regenerated - can you submit a pr to revision bump the formula ?

**Comment by javian** [comment]
This should be fixed now after updating the apr-util bottle.
