### ISSUE TITLE
/usr/local/etc/apache2/2.4 directory not created

### ISSUE THREAD

**Issue by nickwph** [Homebrew/homebrew-apache#136]
Error occurred when I tried to start apache after installing `httpd24` with `brew install homebrew/apache/httpd24`.

```
$ apachectl start
httpd: Could not open configuration file /usr/local/etc/apache2/2.4/httpd.conf: No such file or directory
```

I found that `/usr/local/etc/apache2/2.4` was not created in the process of installing `httpd24`.

What i did is using an older script (from an older commit) to install it, which will create that directory.
```
brew install -v https://raw.githubusercontent.com/Homebrew/homebrew-apache/7f75f548c89ee0bffab92e75399ee00ddf727a0c/httpd24.rb
```

Please fix it! 😄

**Comment by srigi** [comment]
This is super annoying since latest PHP builds require brewing `--with-apache` which fails on this. I kindly requesting this too.

**Comment by javian** [comment]
This should be solved by recreating the bottle. The cause is a bug in brew that existed around the time the previous bottle was created. I've issued #137 to recreate the bottles. It would probably be a good idea to create a test case that checks for this so that it would detect a similar problem in the future.

**Comment by javian** [comment]
@nickwph @srigi did you manage to test this ?

**Comment by nickwph** [comment]
@javian i just tried to install http24 with the formula in https://github.com/Homebrew/homebrew-apache/pull/137. so far it works on my computer. the directory /usr/local/etc/apache2/2.4 was created in the process.

thank you for updating it. 😄 
PR is closed for some reason? is it gonna be another PR?

FYI, this is the console output.
```
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-apache/2a2ae25a46f37dbc055c02a12d910a4f4000ec58/httpd24.rb
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
highlight

######################################################################## 100.0%
==> Downloading https://homebrew.bintray.com/bottles/httpd24-2.4.23_2.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "httpd24"
Download failed: https://homebrew.bintray.com/bottles/httpd24-2.4.23_2.sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://archive.apache.org/dist/httpd/httpd-2.4.23.tar.bz2
######################################################################## 100.0%
==> ./configure --enable-layout=Homebrew --enable-mods-shared=all --enable-unique-id --enable-ssl --enable-dav --enable-cache --enable-
==> make
==> make install
==> Caveats
To have launchd start httpd24 now and restart at login:
  brew services start httpd24
Or, if you don't want/need a background service you can just run:
  apachectl start
==> Summary
🍺  /usr/local/Cellar/httpd24/2.4.23_2: 210 files, 4.2M, built in 1 minute 59 seconds
```

**Comment by javian** [comment]
@nickwph the merge has already been done it just doesn't show in the interface since its done through brew. Check the commit log and you'll see it there.
