### ISSUE TITLE
--with-privileged-ports and envvars

### ISSUE THREAD

**Issue by iloveitaly** [Homebrew/homebrew-apache#148]
Hello! Thanks for this great brew tap. Very helpful.

I'm running into an issue with the `--with-privileged-ports` build option. Here's the situation:

* I have some custom vars in `/usr/local/etc/apache2/2.4/envvars`
* Running apache via `apachectl start` works fine
* `sudo brew services start httpd24` fails. The service fails to pick up on the custom vars.
* `/usr/local/opt/httpd24/bin/httpd -D FOREGROUND` also fails for the same reason

Is there anyway for the `httpd` command in the launchctl plist to pick up on the `envvars`?

Thanks!

**Comment by javian** [comment]
If you look at `apachectl` you will see that's its a bash script that calls on the httpd binary that sources the envvars file. The service file calls the httpd binary directly so without modifying the plist it is not possible. 

If you examine the system plist for apache `/System/Library/LaunchDaemons/org.apache.httpd.plist` you will see that they use a wrapper `/usr/sbin/httpd-wrapper` so you should be able to write your own wrapper and create a plist that laucnhes that in a similar way as `brew services` does to properly load the envars.

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated in favour of the `httpd` formula installed and working after https://github.com/Homebrew/homebrew-core/pull/17726 (which works on Sierra and High Sierra). We're not supporting `--with-privileged ports` there but you can manually add it to your configuration.
