### ISSUE TITLE
Error after brew update/upgrade

### ISSUE THREAD

**Issue by batenburg** [Homebrew/homebrew-apache#150]
After brew update/upgrade it returns the following error:

dyld: Symbol not found: _apr_crypto_block_cleanup
  Referenced from: /usr/local/Cellar/httpd24/2.4.25/bin/httpd
  Expected in: /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib
 in /usr/local/Cellar/httpd24/2.4.25/bin/httpd
/usr/local/bin/apachectl: line 79:  5848 Abort trap: 6           $HTTPD -k $ARGV

**Comment by kernel-task** [comment]
Ditto.
All the usual thing appear OK (brew doctor,cleanup etc)

**Comment by shaoshiqiang** [comment]
I have solved the problem.
step 1 ： brew uninstall --ignore-dependencies apr-util
step 2：  brew uninstall --ignore-dependencies httpd24
step 3：  brew install httpd24

**Comment by batenburg** [comment]
shaoshiqiang has solved it :D

**Comment by javian** [comment]
This is strange since the latest apr and apr-util are already in homebrew.
