### ISSUE TITLE
Unable to start apache after update

### ISSUE THREAD

**Issue by discern** [Homebrew/homebrew-apache#152]
`brew services restart homebrew/apache/httpd24` reports:

```
Stopping `httpd24`... (might take a while)
==> Successfully stopped `httpd24` (label: homebrew.mxcl.httpd24)
==> Successfully started `httpd24` (label: homebrew.mxcl.httpd24)
```
But there is no response on 127.0.0.1. Using the old command `sudo apachectl -k graceful` produces the following error:

```
dyld: Symbol not found: _apr_crypto_block_cleanup
  Referenced from: /usr/local/Cellar/httpd24/2.4.25/bin/httpd
  Expected in: /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib
 in /usr/local/Cellar/httpd24/2.4.25/bin/httpd
/usr/local/bin/apachectl: line 79:   767 Trace/BPT trap: 5       $HTTPD "$@"
```
What gives? (This started happening yesterday—I believe after an OS X security update).

OS X 10.11.6. Brew is updated and all brew packages are up to date.

Introducing an intentional syntax error in httpd.conf does *not* produce an error when starting httpd via brew services.

**Comment by mtughan** [comment]
I had the same issue. Reinstalling from source (using "brew reinstall -s httpd24") fixed it. I think something's wrong with the bottle for this version.

**Comment by discern** [comment]
Yes. That was it—and the one thing I didn't try. Thank you.
