### ISSUE TITLE
No `apr-1-config` anywhere on macOS 10.12

### ISSUE THREAD

**Issue by ugultopu** [Homebrew/homebrew-apache#153]
I am trying to install 'mod_wsgi' but I am getting the following error:

    apxs:Error: /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/apr-1-config not found!.

Now, it is stated that the location for `apr-1-config` has changed but I can't find it anywhere on my system.

    find /Applications/Xcode.app/Contents/Developer -name 'apr-1-config'

does not return anything for me.

    which apr-1-config

does not return anything for me as well.

What should I do?

Regards

**Comment by ilovezfs** [comment]
Feel free to take https://github.com/Homebrew/homebrew-apache/pull/147 for a spin.
```
brew pull https://github.com/Homebrew/homebrew-apache/pull/147
```

**Comment by ugultopu** [comment]
@ilovezfs Worked. But why isn't this PR merged?

**Comment by ilovezfs** [comment]
Because we'll probably just punt and outright require you install httpd24 (or 22) rather than "fixing" it as that PR does.

**Comment by ugultopu** [comment]
@ilovezfs Btw, with 24 and 22, do you mean the patch version (the field after the second dot)? Because `httpd -v` already outputs `Server version: Apache/2.4.23 (Unix)` on my system. In other words, if I already have `httpd24` (per the MAJOR.MINOR), then why didn't the formula worked without merging the PR?

**Comment by ilovezfs** [comment]
You'd probably need to have been passing `--with-homebrew-httpd24`

**Comment by ugultopu** [comment]
@ilovezfs But I am not using the Homebrew's `httpd`. I am using the stock `httpd`. It is located at `/usr/sbin/httpd`.

**Comment by ilovezfs** [comment]
@ugultopu ah. Well that's what I mean by "punting." We'd be requiring the brew version be used.
