### ISSUE TITLE
Throwing error while apche start - Symbol not found: _apr_stat$INODE64\n

### ISSUE THREAD

**Issue by satyagv557** [Homebrew/homebrew-apache#155]
OS: Sierra
We have 2 versions of Apache (2.4.23 by default) and 2.2.21 manually installed to run my application.
Node: v6.10
npm: 3.10

Steps to install the Apache:

cd /Users/Shared/Development/Software/httpd-2.2.31
./configure --prefix=/usr/local/apache2.2 --with-apxs=/usr/sbin/apxs
make
make install

httpd: Syntax error on line 122 of /Users/Shared/Development/env/local/cust/httpd-b2c/conf/httpd.conf: Cannot load /Users/Shared/Development/env/local/cust/httpd-b2c/modules/mod_rewrite.so into server: dlopen(/Users/Shared/Development/env/local/cust/httpd-b2c/modules/mod_rewrite.so, 10): Symbol not found: _apr_stat$INODE64\n  Referenced from: /Users/Shared/Development/env/local/cust/httpd-b2c/modules/mod_rewrite.so\n  Expected in: flat namespace\n in /Users/Shared/Development/env/local/cust/httpd-b2c/modules/mod_rewrite.so

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated, sorry.
