### ISSUE TITLE
mod_fastcgi fails to install

### ISSUE THREAD

**Issue by jbogdani** [Homebrew/homebrew-apache#159]
Hello, I tried to `brew install mod_fastcgi` and I get this:

```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from c08250b9 to e9947fb4.
No changes to formulae.

==> Installing mod_fastcgi from homebrew/apache
==> Downloading https://dl.bintray.com/homebrew/mirror/mod_fastcgi-2.4.6.tar.gz
Already downloaded: /Users/jbogdani/Library/Caches/Homebrew/mod_fastcgi-2.4.6.tar.gz
==> /usr/sbin/apxs -o mod_fastcgi.so -c *.c
Last 15 lines from /Users/jbogdani/Library/Logs/Homebrew/mod_fastcgi/01.apxs:
2017-03-31 11:58:55 +0200

/usr/sbin/apxs -o mod_fastcgi.so -c *.c

apxs:Error: /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.12.xctoolchain/usr/local/bin/apr-1-config not found!.

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
mod_fastcgi: apply Apache 2.4 patch on Yosemite and later https://github.com/Homebrew/homebrew-apache/pull/156
mod_fastcgi not building on OSX 10.11 https://github.com/Homebrew/homebrew-apache/issues/90
mod_fastcgi: The patch should be applied for El Capitan as well https://github.com/Homebrew/homebrew-apache/pull/84
homebrew/apache/mod_fastcgi failed to build on 10.11.2 https://github.com/Homebrew/homebrew-apache/issues/105
```
Tried to follow the tutorial in https://github.com/Homebrew/homebrew-apache#troubleshooting and run the single line solution suggested: `sw_vers -productVersion | grep -E '^10\.([89]|10)' >/dev/null && bash -c "[ -d /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain ] && sudo -u $(ls -ld /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain | awk '{print $3}') bash -c 'ln -vs XcodeDefault.xctoolchain /Applications/Xcode.app/Contents/Developer/Toolchains/OSX$(sw_vers -productVersion).xctoolchain' || sudo bash -c 'mkdir -vp /Applications/Xcode.app/Contents/Developer/Toolchains/OSX$(sw_vers -productVersion).xctoolchain/usr && for i in bin include lib libexec share; do ln -s /usr/${i} /Applications/Xcode.app/Contents/Developer/Toolchains/OSX$(sw_vers -productVersion).xctoolchain/usr/${i}; done'"` but it did not work.

I'm still getting the same error. I'm running brew 1.1.11-218-ge9947fb4 on MacOS 10.12.4 (16E195).
Thank you

**Comment by donnamcmaster** [comment]
I'm getting a very similar error. I'm running brew 1.2.0-66-g459fef3b0
Homebrew/homebrew-core (git revision 6a347; last commit 2017-05-11)
 on MacOS 10.10.5 (14F2315). 

`$ brew update
Already up-to-date.
$ brew doctor
Your system is ready to brew.
$ brew install mod_fastcgi
==> Installing mod_fastcgi from homebrew/apache
==> Downloading https://dl.bintray.com/homebrew/mirror/mod_fastcgi-2.4.6.tar.gz
Already downloaded: /Users/donna/Library/Caches/Homebrew/mod_fastcgi-2.4.6.tar.gz
==> Downloading https://raw.githubusercontent.com/ByteInternet/libapache-mod-fastcgi/byte/debian/patches/byte-compile-again
Already downloaded: /Users/donna/Library/Caches/Homebrew/mod_fastcgi--patch-e405f365fac2d80c181a7ddefc9c6332cac7766cb9c67c464c272d595cde1800.diff
==> Patching
==> Applying byte-compile-against-apache24.diff
patching file fcgi.h
Hunk #3 succeeded at 362 (offset -13 lines).
patching file mod_fastcgi.c
Hunk #2 succeeded at 2971 (offset -47 lines).
==> /usr/sbin/apxs -o mod_fastcgi.so -c *.c
Last 15 lines from /Users/donna/Library/Logs/Homebrew/mod_fastcgi/01.apxs:
2017-05-11 17:18:35 -0700

/usr/sbin/apxs -o mod_fastcgi.so -c *.c

/usr/share/apr-1/build-1/libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.10.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1   -c -o fcgi_buf.lo fcgi_buf.c && touch fcgi_buf.slo
/usr/share/apr-1/build-1/libtool: line 1111: /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.10.xctoolchain/usr/bin/cc: No such file or directory
apxs:Error: Command failed with rc=65536.

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
mod_fastcgi fails to install https://github.com/Homebrew/homebrew-apache/issues/159
mod_fastcgi: apply Apache 2.4 patch on Yosemite and later https://github.com/Homebrew/homebrew-apache/pull/156
mod_fastcgi not building on OSX 10.11 https://github.com/Homebrew/homebrew-apache/issues/90
mod_fastcgi: The patch should be applied for El Capitan as well https://github.com/Homebrew/homebrew-apache/pull/84
homebrew/apache/mod_fastcgi failed to build on 10.11.2 https://github.com/Homebrew/homebrew-apache/issues/105
`

**Comment by donnamcmaster** [comment]
Per https://github.com/Homebrew/homebrew-apache/issues/90, I added "--with-homebrew-httpd24" to the command. 

`brew install --with-homebrew-httpd24 mod_fastcgi`

This time the installation completed successfully. There were Caveats: 
`==> Caveats
You must manually edit /usr/local/etc/apache2/2.4/httpd.conf to contain:
  LoadModule fastcgi_module /usr/local/opt/mod_fastcgi/libexec/mod_fastcgi.so

Upon restarting Apache, you should see the following message in the error log:
  [notice] FastCGI: process manager initialized
`
I edited httpd.conf per the instructions. However, When I tried to restart Apache, I got an LDAP-related error in `/usr/local/Cellar/php56/5.6.30_6/libexec/apache2/libphp5.so`. So I am now on to the next issue.

**Comment by EricFromCanada** [comment]
The currently-suggested single line solution won't work, use this instead:
`[ -d /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain ] && sudo -u $(ls -ld /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain | awk '{print $3}') bash -c 'ln -vs XcodeDefault.xctoolchain /Applications/Xcode.app/Contents/Developer/Toolchains/OSX$(sw_vers -productVersion | cut -d . -f 1,2).xctoolchain' || sudo bash -c 'mkdir -vp /Applications/Xcode.app/Contents/Developer/Toolchains/OSX$(sw_vers -productVersion | cut -d . -f 1,2).xctoolchain/usr && for i in bin include lib libexec share; do ln -s /usr/${i} /Applications/Xcode.app/Contents/Developer/Toolchains/OSX$(sw_vers -productVersion | cut -d . -f 1,2).xctoolchain/usr/${i}; done'`

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated, sorry.
