### ISSUE TITLE
brew install httpd24 error

### ISSUE THREAD

**Issue by tyrone782** [Homebrew/homebrew-apache#161]
brew version: 1.1.13

> brew install httpd24 
Error: Calling Formula.sha1 is disabled!
Use Formula.sha256 instead.
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-apache/httpd24.rb:6:in `<class:Httpd24>'
Please report this to the homebrew/apache tap!
If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/Homebrew/homebrew-apache/issues

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated in favour of the `httpd` formula installed and working after https://github.com/Homebrew/homebrew-core/pull/17726 (which works on Sierra and High Sierra).
