### ISSUE TITLE
Build attempt of latest apache24 on MAC 10.12.4 (16E195)

### ISSUE THREAD

**Issue by Andres-M-Rios** [Homebrew/homebrew-apache#162]
[output.txt](https://github.com/Homebrew/homebrew-apache/files/945762/output.txt)

==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Installing httpd24 from homebrew/apache
==> Downloading https://archive.apache.org/dist/httpd/httpd-2.4.25.tar.bz2
Already downloaded: /Users/andres/Library/Caches/Homebrew/httpd24-2.4.25.tar.bz2
==> ./configure --enable-layout=Homebrew --enable-mods-shared=all --enable-unique-id --enable-ssl --enable-dav --enable-cache --enable-logio --enable-deflate --enable-cgi --enable-cgid --enable-suexec --enable-rewrite --with-apr=/usr/local/opt/apr --with-apr-util=/usr/local/opt/apr-util --with-pcre=/usr/local/opt/pcre --with-ssl=/usr/local/opt/openssl --with-z=/usr/local/opt/zlib --with-mpm=prefork --with-port=80 --with-sslport=443 --enable-http2 --with-nghttp2=/usr/local/opt/nghttp2
==> make
Last 15 lines from /Users/andres/Library/Logs/Homebrew/httpd24/02.make:
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=compile clang  -g -O2      -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10     -I. -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/os/unix -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/include -I/usr/local/opt/apr/libexec/include/apr-1 -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/opt/openssl/include -I/usr/local/Cellar/pcre/8.40/include -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/aaa -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/cache -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/core -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/database -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/filters -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/ldap -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/server -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/loggers -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/lua -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/proxy -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/session -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/ssl -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/test -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/server -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/arch/unix -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/dav/main -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/generators -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/mappers  -prefer-non-pic -static -c checkgid.c && touch checkgid.lo
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=compile clang  -g -O2      -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10     -I. -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/os/unix -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/include -I/usr/local/opt/apr/libexec/include/apr-1 -I/usr/local/opt/apr-util/libexec/include/apr-1 -I/usr/local/opt/openssl/include -I/usr/local/Cellar/pcre/8.40/include -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/aaa -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/cache -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/core -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/database -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/filters -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/ldap -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/server -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/loggers -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/lua -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/proxy -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/session -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/ssl -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/test -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/server -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/arch/unix -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/dav/main -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/generators -I/private/tmp/httpd24-20170420-41435-1ozispe/httpd-2.4.25/modules/mappers  -prefer-non-pic -static -c fcgistarter.c && touch fcgistarter.lo
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2      -L/usr/local/opt/openssl/lib   -o htpasswd  htpasswd.lo passwd_common.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread 
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2      -L/usr/local/opt/openssl/lib   -o htdigest  htdigest.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2      -L/usr/local/opt/openssl/lib   -o htdbm  htdbm.lo passwd_common.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread 
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2   -L/usr/local/opt/openssl/lib -lssl -lcrypto -lpthread  \
	      -L/usr/local/opt/openssl/lib   -o ab  ab.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread 
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2      -L/usr/local/opt/openssl/lib   -o logresolve  logresolve.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2      -L/usr/local/opt/openssl/lib   -o httxt2dbm  httxt2dbm.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ab] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
brew install httpd24 error https://github.com/Homebrew/homebrew-apache/issues/161
httpd24 build fails on yosemite https://github.com/Homebrew/homebrew-apache/issues/75
httpd24 on Yosemite Mac OS ( 10.10.3) occurs segmentation fault https://github.com/Homebrew/homebrew-apache/issues/71

**Comment by Andres-M-Rios** [comment]
Also tried the fix for the Toolchain, still getting this:
==> Auto-updated Homebrew!
Updated 1 tap (caskroom/cask).
No changes to formulae.

==> Installing httpd24 from homebrew/apache
==> Downloading https://archive.apache.org/dist/httpd/httpd-2.4.25.tar.bz2
Already downloaded: /Users/andres/Library/Caches/Homebrew/httpd24-2.4.25.tar.bz2
==> ./configure --enable-layout=Homebrew --enable-mods-shared=all --enable-unique-id --enable-ssl --enable-dav --enable-cache --enable-logio --enable-deflate --enable-cgi --enable-cgid --enable-suexec --enable-rewrite --with-apr=/usr/local/opt/apr --with-apr-util=/usr/local/opt/apr-util --with-pcre=/usr/local/opt/pcre --with-ssl=/usr/local/opt/openssl --with-z=/usr/local/opt/zlib --with-mpm=prefork --with-port=80 --with-sslport=443 --enable-http2 --with-nghttp2=/usr/local/opt/nghttp2
==> make
Last 15 lines from /Users/andres/Library/Logs/Homebrew/httpd24/02.make:
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2      -L/usr/local/opt/openssl/lib   -o htdbm  htdbm.lo passwd_common.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2      -L/usr/local/opt/openssl/lib   -o logresolve  logresolve.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2      -L/usr/local/opt/openssl/lib   -o httxt2dbm  httxt2dbm.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2      -L/usr/local/opt/openssl/lib   -o htcacheclean  htcacheclean.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2      -L/usr/local/opt/openssl/lib   -o rotatelogs  rotatelogs.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2      -L/usr/local/opt/openssl/lib   -o checkgid  checkgid.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2      -L/usr/local/opt/openssl/lib   -o fcgistarter  fcgistarter.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
/usr/local/opt/apr/libexec/build-1/libtool --silent --mode=link clang  -g -O2   -L/usr/local/opt/openssl/lib -lssl -lcrypto -lpthread  \
              -L/usr/local/opt/openssl/lib   -o ab  ab.lo      /usr/local/opt/apr-util/libexec/lib/libaprutil-1.la -lexpat -liconv /usr/local/opt/apr/libexec/lib/libapr-1.la -lpthread
ld: library not found for -lssl
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [ab] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1

READ THIS: http://docs.brew.sh/Troubleshooting.html

These open issues may also help:
brew install httpd24 error https://github.com/Homebrew/homebrew-apache/issues/161
httpd24 build fails on yosemite https://github.com/Homebrew/homebrew-apache/issues/75
httpd24 on Yosemite Mac OS ( 10.10.3) occurs segmentation fault https://github.com/Homebrew/homebrew-apache/issues/71

**Comment by javian** [comment]
Does `brew doctor` give you any hints ? Its missing/can't find an ssl library but that should be installed through the required openssl Formula.

**Comment by churcho** [comment]
I am also hitting this same error.

**Comment by Andres-M-Rios** [comment]
Ya, brew doctor did give me a hint. It wasn't in my path. I've added it to my path, but I have switched to using a Linux install for my web-dev work.

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated in favour of the `httpd` formula installed and working after https://github.com/Homebrew/homebrew-core/pull/17726 (which works on Sierra and High Sierra).
