### ISSUE TITLE
apache2 error_log "exit signal Floating point exception (8)" every time i enable a drupal 7 module and refresh page.

### ISSUE THREAD

**Issue by sekayasin** [Homebrew/homebrew-apache#171]
Hello, Any one seen this apache2 error_log 

[core:notice] [pid 4123] AH00052: child pid 51208 exit signal Floating point exception (8)
[core:notice] [pid 4123] AH00052: child pid 51207 exit signal Floating point exception (8)
[core:notice] [pid 4123] AH00052: child pid 51206 exit signal Floating point exception (8)
[core:notice] [pid 4123] AH00052: child pid 51205 exit signal Floating point exception (8)
[core:notice] [pid 4123] AH00052: child pid 51211 exit signal Floating point exception (8)
[core:notice] [pid 4123] AH00052: child pid 51212 exit signal Floating point exception (8)

i'm running homebrew's httpd24 and php71, AMP stack on OSX 10.11 is very fine. ,but i get this error every time i install i enable a drupal7 module, and refresh page i get this in the browser,
                      This page isn’t working
                       localhost didn’t send any data.
                       ERR_EMPTY_RESPONSE  
but when i drush dis module, everything is fine. :) 
Anyone seen this,

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated in favour of the `httpd` formula installed and working after https://github.com/Homebrew/homebrew-core/pull/17726 (which works on Sierra and High Sierra).
