### ISSUE TITLE
Add option for enable mpms shared

### ISSUE THREAD

**Issue by Dief** [Homebrew/homebrew-apache#174]
Would an option to configure with --enable-mpms-shared=all be welcome to the httpd recipe? Would be happy to contribute, just wanted to first get a sense of any interest (other than my own).

**Comment by kabel** [comment]
In the works at #170

**Comment by Dief** [comment]
Oh nice. Thanks.

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated in favour of the `httpd` formula installed and working after https://github.com/Homebrew/homebrew-core/pull/17726 (which works on Sierra and High Sierra and has this option).
