### ISSUE TITLE
macOS's built-in tools for building Apache modules don't work

### ISSUE THREAD

**Issue by EricFromCanada** [Homebrew/homebrew-apache#177]
In short: The `apxs`, `apr-1-config`, and `libtool` that ship with macOS's Apache have hard-coded a wrong toolchain path that can't be overridden, preventing modules from building.

In detail: The `apxs` tool helps compile Apache modules by calling its own copy of `libtool` to compile and link. But if we try to compile [any module](https://jenkins.brew.sh/job/Homebrew%20Apache%20Pull%20Requests/version=el_capitan/lastCompletedBuild/testReport/brew-test-bot/el_capitan/install_homebrew_apache_mod_fastcgi/) with it, it fails immediately with

```
$ /usr/sbin/apxs -o mod_bonjour.so -c *.c
/usr/share/apr-1/build-1/libtool --silent --mode=compile /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.11.xctoolchain/usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1   -c -o mod_bonjour2.lo mod_bonjour2.c && touch mod_bonjour2.slo
/usr/share/apr-1/build-1/libtool: line 1111: /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.11.xctoolchain/usr/bin/cc: No such file or directory
apxs:Error: Command failed with rc=65536
```

If we examine the source of `/usr/sbin/apxs`, we see it's reading the list of variables in `/usr/share/httpd/build/config_vars.mk`, which sets `CC` and `CPP` to be within the non-existent `/Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.n.xctoolchain` directory (where `n` is macOS's minor version number), as it has [since OS X 10.8](https://stackoverflow.com/questions/11963436/changing-apr-embedded-values-returned-by-apr-1-config), while the actual path to Xcode's toolchain directory is `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain`. The current recommendation made by this tap's README has been to [manually add a symlink](https://github.com/Homebrew/homebrew-apache#troubleshooting) so named to point to the proper directory. This works, but it's a hack.

`apxs` only passes `CC` to `libtool`, and it's possible to override this value using the `-S` flag. However, it then fails at the link stage:

```
$ /usr/sbin/apxs -S CC=/usr/bin/cc -o mod_bonjour.so -c *.c
/usr/share/apr-1/build-1/libtool --silent --mode=compile /usr/bin/cc    -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.Internal.sdk/usr/include/apr-1  -I/usr/include/apache2  -I/usr/include/apr-1   -I/usr/include/apr-1   -c -o mod_bonjour2.lo mod_bonjour2.c && touch mod_bonjour2.slo
...
8 warnings generated.
/usr/share/apr-1/build-1/libtool --silent --mode=link /usr/bin/cc    -o mod_bonjour.la  -rpath /usr/libexec/apache2 -module -avoid-version    mod_bonjour2.lo
/usr/share/apr-1/build-1/libtool: line 8962: /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.11.xctoolchain/usr/bin/cc: No such file or directory
apxs:Error: Command failed with rc=8323072
```

This shows `/usr/share/apr-1/build-1/libtool` is ignoring the passed `CC` path for the link stage. Looking at the script's source, it starts by setting several variables, including `LTCC`, `sys_lib_search_path_spec`, `LD`, and `CC`, all of which use the wrong toolchain path. Only its own `CC` is used in this case, starting on line 355, and unless I'm missing something there doesn't appear to be a way of overriding that value.

Is it possible to make `apxs` use a brewed `libtool` instead? Apparently not, because it uses the value of `/usr/bin/apr-1-config --apr-libtool`, the path to which is derived from `APR_CONFIG` in `config_vars.mk`, which itself hard-codes the `libtool` path (and also sets wrong paths for `CC` and `CPP`, although these aren't used in this case). 

All the modules in this tap fail to build on OS X 10.8 and later unless the hack mentioned above is applied. So far, the cleanest fix I've found is to have each formula compile its module using `apxs` but ignore the return code (since the link step will fail and it's not possible to have `apxs` just compile a module), then manually link using a brewed GNU libtool. Using [mod_bonjour](https://github.com/Homebrew/homebrew-apache/blob/b46fe1db9b976c2b52196eb9899838ca56efede4/mod_bonjour.rb#L64-L65) as an example:

```
    system "#{apache_apxs} -o mod_bonjour.so -S CC=/usr/bin/cc -c *.c || :"
    system Formula["libtool"].bin/"glibtool" " --tag=CC --mode=link /usr/bin/cc -o mod_bonjour.la -rpath /usr/libexec/apache2 -module -avoid-version mod_bonjour2.lo"
    libexec.install ".libs/mod_bonjour.so"
```

(These changes would need to only take effect if not building with homebrew-httpd22 or homebrew-httpd24.)

Can anyone suggest improvements? Did I miss anything?

**Comment by ilovezfs** [comment]
@EricFromCanada see https://github.com/Homebrew/homebrew-apache/pull/147/files

Just requiring httpd24 from now on is probably the path forward.

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated in favour of the `httpd` formula installed and working after https://github.com/Homebrew/homebrew-core/pull/17726 (which works on Sierra and High Sierra).
