### ISSUE TITLE
Cannot tap homebrew/apache in macOS High Sierra 10.13

### ISSUE THREAD

**Issue by exequiel09** [Homebrew/homebrew-apache#179]
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-apache/mod_suexec.rb
formulae require at least a URL

<img width="771" alt="screen shot 2017-09-27 at 10 54 27 am" src="https://user-images.githubusercontent.com/1289472/30893734-5e0a3bd0-a372-11e7-9dfc-12f247ab998d.png">

**Comment by fandasson** [comment]
I have the same problem. Pull request #172 fixes this. I tried it on custom fork which allows me to install apache with brew, but php packages still depends on this tap so I can't run 
`brew install php56 --with-httpd24`

**Comment by 20kmfoto** [comment]
+1

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated in favour of the `httpd` formula installed and working after https://github.com/Homebrew/homebrew-core/pull/17726 (which works on Sierra and High Sierra).
