### ISSUE TITLE
Cannot install http24 directly on macOS High Sierra 10.13

### ISSUE THREAD

**Issue by exequiel09** [Homebrew/homebrew-apache#180]
Since i can't tap homebrew/apache due to #179, i tried to use the command `brew install https://github.com/Homebrew/homebrew-apache/blob/master/httpd24.rb` to install Apache 2.4.

<img width="1053" alt="screen shot 2017-09-27 at 11 03 44 am" src="https://user-images.githubusercontent.com/1289472/30893993-a1093f70-a373-11e7-817e-e12b370c25a2.png">

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated in favour of the `httpd` formula installed and working after https://github.com/Homebrew/homebrew-core/pull/17726 (which works on Sierra and High Sierra).
