### ISSUE TITLE
Apache 2.2 on OS X Yosemite

### ISSUE THREAD

**Issue by frankreno** [Homebrew/homebrew-apache#58]
I am not able to install 2.2 on yosemite...below is the output...

Franks-MacBook-Pro-2:~ frankreno$ brew install homebrew/apache/httpd22
==> Installing httpd22 from homebrew/homebrew-apache
==> Downloading https://archive.apache.org/dist/httpd/httpd-2.2.29.tar.bz2
Already downloaded: /Library/Caches/Homebrew/httpd22-2.2.29.tar.bz2
==> Patching
==> ./configure --enable-layout=Homebrew --enable-mods-shared=all --enable-unique-id --enable-ssl --enable-dav --enable-cache --enable-proxy --enable-logio --enable-deflate --enable-cgi --enable-cgid
==> make
/usr/local/Cellar/apr/1.5.1/build-1/libtool --silent --mode=link clang -g -O2 -Wall    -L/usr/local/opt/zlib/lib -L/usr/lib      -o mod_imagemap.la -rpath /usr/local/Cellar/httpd22/2.2.29/libexec -module -avoid-version  mod_imagemap.lo 
/usr/local/Cellar/apr/1.5.1/build-1/libtool --silent --mode=link clang -g -O2 -Wall    -L/usr/local/opt/zlib/lib -L/usr/lib      -o mod_negotiation.la -rpath /usr/local/Cellar/httpd22/2.2.29/libexec -module -avoid-version  mod_negotiation.lo 
/usr/local/Cellar/apr/1.5.1/build-1/libtool --silent --mode=link clang -g -O2 -Wall    -L/usr/local/opt/zlib/lib -L/usr/lib      -o mod_rewrite.la -rpath /usr/local/Cellar/httpd22/2.2.29/libexec -module -avoid-version  mod_rewrite.lo 

make: *** [all-recursive] Error 1

**Comment by alanthing** [comment]
Are there any files under /usr/local/ that are owned by root or another user other than `whoami`?

**Comment by frankreno** [comment]
There is, I just changed it to whoami and re ran.  Still getting the same error.

**Comment by alanthing** [comment]
Oops, sorry, I meant '`whoami`', meaning the result of the whoami command, or your short unix user name.

**Comment by frankreno** [comment]
Yeah I got what you mean :) It was root, i changed it to my username.

**Comment by alanthing** [comment]
Run the following commands and then try and install again:

```
xcode-select --print-path
sudo xcode-select --switch /Library/Developer/CommandLineTools
xcode-select --print-path
```

Back on 10.9, some folks with strange compilation problems had better luck by switching the compiler to the one provided by the Command Line Tools package instead of Xcode. I don't think that's the problem, but it's a troubleshooting step you can certainly try (the `print-path` before and after is to confirm if a change is actually being made).

**Comment by frankreno** [comment]
Here is the results of the above command...the change is not being made, looks like I don't have /Library/Developer/CommandLineTools.  This machine is a clean 10.10 install, not upgraded from 10.9...

**Comment by alanthing** [comment]
See http://railsapps.github.io/xcode-command-line-tools.html or another guide and try installing the Xcode Command Line Tools package. Some users have reported success with that over the full Xcode utilities.

**Comment by fransflippo** [comment]
This worked for me! Thanks!

**Comment by alanthing** [comment]
Great. Thanks for reporting back

**Comment by fransflippo** [comment]
BTW I am not the original poster, but I hope it solves the problem for him as well.
