### ISSUE TITLE
Missing dependency on lynx

### ISSUE THREAD

**Issue by Krinkle** [Homebrew/homebrew-apache#59]
I had to downgrade a machine to OS X Lion this week and noticed that httpd22 didn't work properly after due to lynx not being installed.

```
$ brew install httpd22
$ (run documented commands to load the deamon)
$ apachectl status
/usr/local/bin/apachectl: line 94: lynx: command not found
```
```sh
$ cat `which apachectl`
..
LYNX="lynx -dump"
..
status)
    $LYNX $STATUSURL | awk ' /process$/ { print; exit } { print } '
..
```

Maybe it's installed on newer OS X versions by default?

**Comment by alanthing** [comment]
Lynx/links/elinks is not included with Apache on any distro operating system I've ever seen. I'd recommend you run `brew install lynx` and easily enable this feature.
