### ISSUE TITLE
libaprutil error with Apache Bench

### ISSUE THREAD

**Issue by netpoetica** [Homebrew/homebrew-apache#60]
```
➜  project git:(master) ✗ /usr/local/Cellar/ab/2.4.10/bin/ab -V
dyld: Library not loaded: /usr/local/opt/apr-util/lib/libaprutil-1.0.dylib
  Referenced from: /usr/local/Cellar/ab/2.4.10/bin/ab
  Reason: Incompatible library version: ab requires version 6.0.0 or later, but libaprutil-1.0.dylib provides version 4.0.0
[1]    13134 trace trap  /usr/local/Cellar/ab/2.4.10/bin/ab -V
```
I am having a lot of difficulty figuring out what is causing this issue.

Sys Info:
```
Darwin Kernel Version 12.5.0: Sun Sep 29 13:33:47 PDT 2013; root:xnu-2050.48.12~1/RELEASE_X86_64 x86_64
```

Brew is most-recent (updated today). My brew doctor does have some strange dylib warnings but they are just warnings:

```
➜  project git:(master) ✗ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
    /usr/local/lib/libsfml-audio.2.1.dylib
    /usr/local/lib/libsfml-graphics.2.1.dylib
    /usr/local/lib/libsfml-network.2.1.dylib
    /usr/local/lib/libsfml-system.2.1.dylib
    /usr/local/lib/libsfml-window.2.1.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
    /usr/local/include/tidy/buffio.h
    /usr/local/include/tidy/platform.h
    /usr/local/include/tidy/tidy.h
    /usr/local/include/tidy/tidyenum.h
```
I also removed and did a verbose install, but it came from cache - maybe it's helpful:
```
➜  project git:(master) ✗ brew install homebrew/apache/ab --verbose
==> Installing ab from homebrew/homebrew-apache
==> Downloading https://bitbucket.org/alanthing/homebrew-apache/downloads/ab-2.4.10.mountain_lion.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/ab-2.4.10.mountain_lion.bottle.tar.gz
==> Verifying ab-2.4.10.mountain_lion.bottle.tar.gz checksum
==> Pouring ab-2.4.10.mountain_lion.bottle.tar.gz
tar xf /Library/Caches/Homebrew/ab-2.4.10.mountain_lion.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

Mac OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.
==> Finishing up
==> Summary
/usr/local/Cellar/ab/2.4.10: 7 files, 280K
```

**Comment by netpoetica** [comment]
Worth noting - I did successfully install this package a week or so ago on a Yosemite machine

**Comment by netpoetica** [comment]
It also does appear that I have apr and apr-util in both /usr/opt and in /usr/local/(Cellar) - but /usr/local appears in my path first

**Comment by maligree** [comment]
I got the same. Did you work this out, by chance?

**Comment by netpoetica** [comment]
@maligree I do not recall the exact solution, but, I do remember I was running into this during installation of Apache Bench. I remember doing a lot of Google research and stumbling on a couple of different possible solutions, but, I cannot remember which one did it. These are a couple of the articles I recall working with:

- http://adventuresincoding.com/2012/05/how-to-get-apachebenchab-to-work-on-mac-os-x-lion
- https://coderwall.com/p/tthe6a/fix-apachebench-ab-on-mountain-lion (potentially using dupes)
- http://stackoverflow.com/a/21645321

Hope this helps!

Worth noting - even after installing it, I still had a tendency to run into this "connection reset by peer" - I believe it has something to do with 127.0.0.1 vs localhost - use 127.0.0.1 should get the error to disappear.

Cheers

**Comment by alanthing** [comment]
A few months ago, `apr` and `apr-util` moved out of this project and into the mainline Homebrew project. You might want to completely uninstall all three formulas, `brew uninstall --force ab apr apr-util`, and then reinstall after a `brew update`. **Take care running that command**; it's an example, read the text carefully and maybe even check the brew man page to understand what it does before proceeding.

**Comment by javian** [comment]
No information in over a year - closing.
