### ISSUE TITLE
mod_wsgi not loading in apache

### ISSUE THREAD

**Issue by AKFourSeven** [Homebrew/homebrew-apache#61]
Hi I have sucessfully installed apache with brew.
I have tried including mod_wsgi (3.5) in the conf but when I try a apachectl restart I get the following error:

```
httpd: Syntax error on line 169 of /usr/local/etc/apache2/2.4/httpd.conf: Cannot load /usr/local/Cellar/mod_wsgi/3.5/libexec/mod_wsgi.so into server: dlopen(/usr/local/Cellar/mod_wsgi/3.5/libexec/mod_wsgi.so, 10): Symbol not found: _apr_file_info_get$INODE64\n  Referenced from: /usr/local/Cellar/mod_wsgi/3.5/libexec/mod_wsgi.so\n  Expected in: flat namespace\n in /usr/local/Cellar/mod_wsgi/3.5/libexec/mod_wsgi.so
```

Can you provide any guidance ?

**Comment by alanthing** [comment]
Can you show us the command you used to install mod_wsgi into Homebrewed httpd24, and the relevant portions of httpd.conf?

**Comment by alanthing** [comment]
Also, please post the output of both `brew gist-logs httpd24` and `brew gist-logs mod_wsgi`.

**Comment by AKFourSeven** [comment]
httpd.conf was
`LoadModule alias_module libexec/mod_alias.so
LoadModule rewrite_module libexec/mod_rewrite.so
LoadModule php5_module  /usr/local/opt/php56/libexec/apache2/libphp5.so
LoadModule wsgi_module /usr/local/Cellar/mod_wsgi/3.5/libexec/mod_wsgi.so`

and the command I use to install mod_wsgi was
`brew install mod_wsgi`

I will need to reinstall mod_wsgi before I can post the second output.

Here comes the first one:
https://gist.github.com/b2d1a6481172ce6d786c

**Comment by alanthing** [comment]
To use mod_wsgi with a Homebrew-built httpd24, you'll need to install via:

    brew install mod_wsgi --with-brewed-httpd24

See `brew info mod_wsgi` for more information. Try uninstalling the existing mod_wsgi you previously installed, remove any additions to your Homebrew httpd.conf, and then install again with the added flag above.

**Comment by AKFourSeven** [comment]
Thanks for the help, that was really it!

**Comment by alanthing** [comment]
I'm not terribly familiar with the extension or python to say for sure. It does have the `--with-brewed-python` option fwiw. If you notice any problems, feel free to submit a PR for improvements.

**Comment by AKFourSeven** [comment]
Well it was correct I did a `--with-brewed-httpd24`and `--with--brewed-python`, I have another issue which is not related to the brew install anymore, thanks for all your help, I think this ticket can be closed.
