### ISSUE TITLE
Installation of mod_suexec fails under 10.10

### ISSUE THREAD

**Issue by sakra** [Homebrew/homebrew-apache#69]
Error

	==> ./configure LDFLAGS=--tag=cc --enable-suexec=shared --with-suexec-bin=/usr/bin/suexec --with-suexec-caller=_www --with-suexec-userdir=Sites --with-suexec-docroot=/ --with-su
	checking for gcc... clang
	checking whether the C compiler works... no
	configure: error: in `/private/tmp/mod_suexec20150417-12455-t7bs49/httpd-2.4.9':
	configure: error: C compiler cannot create executables
	See `config.log' for more details

	READ THIS: https://git.io/brew-troubleshooting
	If reporting this issue please do so at (not Homebrew/homebrew):
	  https://github.com/homebrew/homebrew-apache/issues

**Comment by sakra** [comment]
Logs https://gist.github.com/04931c2596de02d97585

**Comment by KvanSteijn** [comment]
I have the same issue and logs. Did you find the problem?

**Comment by sakra** [comment]
Nope.

**Comment by alanthing** [comment]
The mod_suexec formula needs a lot of work and I haven't had the time, sorry! I hope to get to it soon.

**Comment by KvanSteijn** [comment]
Many that i can help, what is the problem? Is it the apache version?

**Comment by maxmasetti** [comment]
hi, some news? I cloud help in some way...

**Comment by maxmasetti** [comment]
hi, I downloaded the tar and manually compiled on yosemite: before it makes correctly I had to link 
`# sudo ln -s XcodeDefault.xctoolchain OSX10.10.xctoolchain`
in folder /Applications/Xcode.app/Contents/Developer/Toolchains
and remove --tag=cc from ./configure line.
hope this helps.

**Comment by HapiCZ** [comment]
Problem in Yosemite and El Capitan fixes my pull request
https://github.com/Homebrew/homebrew-apache/pull/86
