### ISSUE TITLE
httpd24 on Yosemite Mac OS ( 10.10.3) occurs segmentation fault

### ISSUE THREAD

**Issue by KentaroArai** [Homebrew/homebrew-apache#71]
I installed httpd24 by following command.
`> brew install httpd24`

I checked the version by following command and I think installation is correct
`/usr/local/bin/apachectl -v
Server version: Apache/2.4.12 (Unix)
Server built:   May  1 2015 14:25:51`

However, when I attempt to start httpd, I got following error.
`/usr/local/bin/apachectl start
/usr/local/bin/apachectl: line 79: 46371 Segmentation fault: 11  $HTTPD -k $ARGV`

Does anyone have any idea that fix above error?

**Comment by bfontaine** [comment]
Is it still an issue with the latest version (`brew upgrade httpd24`)?

**Comment by chrisdeeming** [comment]
Also getting this, does any one have a solution?

**Comment by javian** [comment]
@chrisdeeming are you using a fresh install ?

**Comment by chrisdeeming** [comment]
I got it sorted.

The only thing I did was remove all of the LoadModule directives for mod PHP. I was running multiple PHP versions and it may well be the fact that I had a mix of different SO files defined for the different versions.

So, I removed them all, replaced them with:

```# Brew PHP LoadModule for `sphp` switcher
LoadModule php5_module /usr/local/lib/libphp5.so
#LoadModule php7_module /usr/local/lib/libphp7.so```

And installed the PHP switcher:

```curl -L https://gist.github.com/w00fz/142b6b19750ea6979137b963df959d11/raw > /usr/local/bin/sphp
chmod +x /usr/local/bin/sphp```

**Comment by carstenwawer** [comment]
@chrisdeeming : Same Problem here, I try tu use the exact same PHP Switcher.

**Comment by MikeMcQuaid** [comment]
This formula was migrated to Homebrew/homebrew-core in https://github.com/Homebrew/homebrew-core/pull/17726. This tap is now deprecated.
