### ISSUE TITLE
mod_fastcgi fails with httpd22

### ISSUE THREAD

**Issue by jimmybnsn** [Homebrew/homebrew-apache#72]
I was following @alanthing's tutorial here: 
`https://echo.co/blog/os-x-1010-yosemite-local-development-environment-apache-php-and-mysql-homebrew`

I was unable to get the above tutorial working and found it had something to do with mod_fastcgi, which I found was not installed - installation resulted in this error:
`/usr/share/apr-1/build-1/libtool: line 1111: /Applications/Xcode.app/Contents/Developer/Toolchains/OSX10.10.xctoolchain/usr/bin/cc: No such file or directory
apxs:Error: Command failed with rc=65536`

More can be fond here: https://gist.github.com/anonymous/d7233d69948ca3fe4ab6

**Comment by alanthing** [comment]
https://github.com/Homebrew/homebrew-apache#troubleshooting explains how to solve this.

You shouldn't be seeing this message if you're following my blog post, you should be using *--with-brewed-httpd22*, like: `brew install -v homebrew/apache/mod_fastcgi --with-brewed-httpd22`

**Comment by jimmybnsn** [comment]
You're correct, I didn't have the version flag.  My apologies and thanks.

**Comment by alanthing** [comment]
No worries, you're welcome
