### ISSUE TITLE
Apache http-proxy module doesn't load

### ISSUE THREAD

**Issue by Drewshg312** [Homebrew/homebrew-apache#78]
Trying to setup Elasticsearch+Logstash+Kibana with Apache 2.4.

-- Successfully installed:

    brew install elasticsearch logstash httpd24

-- Enabled virtual hosts module in **/usr/local/etc/apache2/2.4/httpd.conf:**

    # Virtual hosts
    Include /usr/local/etc/apache2/2.4/extra/httpd-vhosts.conf

and

    LoadModule vhost_alias_module libexec/mod_vhost_alias.so

-- Created virtual host in **/usr/local/etc/apache2/2.4/extra/httpd-vhosts.conf**:

    <VirtualHost *:8080>
        ServerName kibana4.serv
        ServerAlias www.kibana4.serv
        DocumentRoot /usr/local/var/www/kibana-4.0.2-darwin-x64/src/public
        <Directory /usr/local/var/www/kibana-4.0.2-darwin-x64/src/public>
            Require all granted
            Allow from all
            Options -MultiViews
        </Directory>
    </VirtualHost>

-- Created new config for ELK **/usr/local/etc/apache2/2.4/other/elk.conf**:

    LoadModule proxy_http_module /usr/local/opt/httpd24/libexec/mod_proxy_http.so
    
    <Location /elasticsearch>
        ProxyPass http://localhost:9200/
        ProxyPassReverse /
        SSLRequireSSL
    </Location>
    
    <Location /kibana/>
        ProxyPass http://localhost:5601/
        ProxyPassReverse /
        SSLRequireSSL
    </Location>

-- Included newly created config **elk.conf** to **/usr/local/etc/apache2/2.4/httpd.conf**:

    Include /usr/local/etc/apache2/2.4/other/*.conf

BUT when I try to restart apache getting:

    $ /usr/local/opt/httpd24/bin/httpd -D FOREGROUND
    httpd: Syntax error on line 523 of /usr/local/etc/apache2/2.4/httpd.conf: 
    Syntax error on line 1 of /usr/local/etc/apache2/2.4/other/elk.conf: 
    Cannot load /usr/local/opt/httpd24/libexec/mod_proxy_http.so into server:
    dlopen(/usr/local/opt/httpd24/libexec/mod_proxy_http.so, 10): 
    Symbol not found: _ap_proxy_cookie_reverse_map\n  
    Referenced from: /usr/local/opt/httpd24/libexec/mod_proxy_http.so\n  
    Expected in: flat namespace\n in /usr/local/opt/httpd24/libexec/mod_proxy_http.so

What's the problem loading mod_proxy_http.so? The path to the module is correct...

**Comment by Drewshg312** [comment]
Well never mind I've addressed this issue

**Comment by ivankennethwang** [comment]
@Drewshg312 how did you fix it?

**Comment by Drewshg312** [comment]
uncomment
`LoadModule proxy_module libexec/mod_proxy.so`
and please let me know if it worked.

**Comment by ivankennethwang** [comment]
apperntly it couldnt find the module... i reverted back using sierra's apache.
