### ISSUE TITLE
Wrong ab version is installed

### ISSUE THREAD

**Issue by pzula** [Homebrew/homebrew-apache#79]
I've installed `ab` using this package in order to get around the `SSL read failed` bug present in the one shipped with OSX, but for some reason, even when I use the bin file in Cellar, I still get this output when running the command: 

```
This is ApacheBench, Version 2.3 <$Revision: 1638069 $>
```

I'm wondering what I'm doing wrong that I still end up with the incorrect version, with the same bug as before. Thoughts? I installed using the commands on the `README`.

**Comment by dzuelke** [comment]
Your `$PATH` order probably finds the bundled `ab` first. Check `which ab` to verify.

**Comment by alanthing** [comment]
`ab` also ships with OS X, and so you might need to explicitly define the full path of the `brew`-installed version, such as `/usr/local/bin/ab`.
