### ISSUE TITLE
brew install homebrew/apache/mod_python does not install the associated python modules

### ISSUE THREAD

**Issue by cmalek** [Homebrew/homebrew-apache#80]
brew install homebrew/apache/mod_python installs `mod_python.so`, but does not install any of the python modules under the `lib` directory in the source distribution.   Those are very necessary for any reasonable mod_python code.

```
lib
└── python
    └── mod_python
        ├── Cookie.py
        ├── Session.py
        ├── __init__.py
        ├── apache.py
        ├── cache.py
        ├── cgihandler.py
        ├── httpdconf.py
        ├── psp.py
        ├── publisher.py
        ├── python22.py
        ├── testhandler.py
        ├── util.py
        └── wsgi.py
```

Is there some other way I'm supposed to use to install that code, or was it just forgotten?

**Comment by alanthing** [comment]
(apologies on the delay, I am planning on investing time into homebrew-apache issues and PRs this weekend)

**Comment by yathit** [comment]
:+1:

**Comment by mljn** [comment]
👍

**Comment by javian** [comment]
Looking at the code it only seems to install the .so so you are probably correct that it is not reflected in the Formula at the moment. Can you have a look at the Formula and see if you can complement it in any way ?

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated, sorry.
