### ISSUE TITLE
mod_fastcgi not building on OSX 10.11

### ISSUE THREAD

**Issue by madhancock** [Homebrew/homebrew-apache#90]
`brew install mod_fastcgi` is resulting in the following compile error.

```
Last 15 lines from /Users/mikehancock/Library/Logs/Homebrew/mod_fastcgi/01.apxs:
#define ap_log_error(...) ap_log_error__(__VA_ARGS__)
                          ^
/usr/include/apache2/http_log.h:366:28: note: expanded from macro 'ap_log_error__'
    do { const server_rec *sr = s; if (APLOG_MODULE_IS_LEVEL(sr, mi, level)) \
                           ^
fcgi_config.c:975:9: error: expected expression
/usr/include/apache2/http_log.h:363:27: note: expanded from macro 'ap_log_error'
#define ap_log_error(...) ap_log_error__(__VA_ARGS__)
                          ^
/usr/include/apache2/http_log.h:367:76: note: expanded from macro 'ap_log_error__'
             ap_log_error_(file, line, mi, level, status, sr, VA_ARGS__);    \
                                                                           ^
6 warnings and 8 errors generated.
apxs:Error: Command failed with rc=65536
```

**Comment by madhancock** [comment]
Turns out `--with-homebrew-httpd24` was required to get it to use the correct apxs during build.

Might it be worth adding more specific instructions for each installation path (`2.2`, `2.4`)?

**Comment by xyng** [comment]
Got the same issue. ``--with-homebrew-httpd24`` solves the build, but the Apache bundled with macOS Sierra will not serve my Sites (Safari says "No connection") but not throw any errors to console.
When I comment out the LoadModule it serves the pages again.
Anyone has a fix for this?

**Comment by kweij** [comment]
Seems like the same issue I run into: #139

**Comment by MikeMcQuaid** [comment]
This tap is now deprecated, sorry.
