### ISSUE TITLE
Apache 2.4.17 has fairly major flaw - suggesting revert

### ISSUE THREAD

**Issue by madhancock** [Homebrew/homebrew-apache#95]
The 2.4.17 release has a known flaw causing it to cripple sites that rely on REDIRECT_URI. 

Documented here: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1367427.html

It's being patched into 2.4.18, but as an interim I suggest reverting homebrew to using the working 2.4.16 release.

**Comment by bfontaine** [comment]
Fixed by #96.
